version: "3.8"
services:
  db:
    image: postgres:16
    container_name: past_the_post_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:

